services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    extra_hosts:
      - "pico:host-gateway"
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/host:ro
    env_file: .env
    depends_on:
      - netstat
      - f1_api
    networks:
      - proxy

  netstat:
    container_name: netstat
    build: ./netstat
    restart: unless-stopped
    network_mode: host
    environment:
      - NETWORK_INTERFACE=${NETWORK_INTERFACE:-eth0}
      - NETSTAT_PORT=8085
    volumes:
      - /sys/class/net:/sys/class/net:ro

  f1_api:
    container_name: f1_api
    image: skyallinott/f1_api:latest
    restart: unless-stopped
    environment:
      - TIMEZONE=UTC
      - TRACK_COLOUR=#e5d486
      - EVENT_DETAIL=main
    networks:
      - proxy

networks:
  proxy:
    external: true
