- name: Home
  columns:
    # Left Column - System Stats & Clock
    - size: small
      widgets:
        - type: search
          search-engine: google
          new-tab: true
          bangs:
          - title: YouTube
            shortcut: "!yt"
            url: https://www.youtube.com/results?search_query={QUERY}
          - title: Chat GPT
            shortcut: "!c"
            url: https://chat.openai.com/?q={QUERY}
        - type: clock
          hour-format: 12h
        - type: calendar
          first-day-of-week: monday
    # Center Column - Docker Containers & Server Stats
    - size: full
      widgets:
      - type: docker-containers
        title: Active Containers
        cache: 5s
        hide-by-default: false
        # show-all-containers: false
        containers:
          jellyfin:
            name: Jellyfin
            icon: si:jellyfin
            url: https://media.jr4.in
          big-bear-open-webui:
            name: Open-WebUI
            icon: mdi:robot
            url: https://chat.jr4.in
          convertx:
            name: ConvertX
            icon: mdi:file-replace-outline
            url: https://convertx.jr4.in
          portainer:
            name: Portainer
            icon: si:portainer
            url: https://portainer.jr4.in
          qbittorrent:
            name: qBittorrent
            icon: si:qbittorrent
            url: https://qbit.jr4.in
          steam-headless:
            name: Steam-Headless
            icon: si:steam
            url: https://game.jr4.in
          glance:
            name: Glance
            icon: si:glance
            url: https://home.jr4.in
            id: glance
          netstat:
            name: NetStat
            parent: glance
            icon: mdi:network
          f1_api:
            name: F1 API
            icon: mdi:formula1
            parent: glance
          vidown-frontend:
            name: Vi[D]own
            icon: mdi:download
            url: https://dl.jr4.in
            id: vidown
          vidown-backend:
            name: Backend
            parent: vidown
          anyconv:
            name: AnyConv
            icon: mdi:swap-horizontal
            url: https://convert.jr4.in
          filemanager-backend:
            name: Backend
            icon: mdi:folder
            parent: filemanager
          filemanager-frontend:
            name: FileManager
            icon: mdi:folder-open
            url: https://filemanager.jr4.in
            id: filemanager
          filemanager-nginx:
            name: Nginx
            icon: mdi:server
            parent: filemanager
          cloudflared:
             name: Cloudflare Tunnel
             icon: mdi:cloud-outline
          postgres:
             name: PostgreSQL
             icon: si:postgresql
          mariadb:
             name: MariaDB
             icon: si:mariadb
          traefik:
             name: Traefik
             icon: si:traefikproxy
             url: https://traefik.jr4.in/dashboard/
          gitea:
             name: Gitea
             icon: si:gitea
             url: https://git.jr4.in
             id: gitea
          gitea-runner:
             name: Runner
             icon: si:circleci
             parent: gitea
          gitlab:
             name: GitLab
             icon: si:gitlab
             url: https://gitlab.jr4.in
             id: gitlab
          gitlab-runner:
             name: Runner
             icon: si:circleci
             parent: gitlab
          excalidraw:
             name: Excalidraw
             icon: mdi:pencil-ruler
             url: https://draw.jr4.in
          swingmusic:
             name: SwingMusic
             icon: mdi:music-note
             url: https://music.jr4.in
          siyuan:
              name: SiYuan
              icon: mdi:notebook
              url: https://siyuan.jr4.in
      - type: split-column
        widgets:
          - type: server-stats
            cache: 1m
            servers:
            - type: local
              name: Pico Server
          - type: extension
            title: Network Usage
            url: http://pico:8085/widget
            cache: 2s
            allow-potentially-dangerous-html: true
          # Right Column - Server Stats & Weather
    - size: small
      widgets:
        - type: weather
          location: Jammu, Jammu and Kashmir, India
          units: metric
          hour-format: 12h
          cache: 30m
        - type: html
          source: |
            <pre style="font-family: monospace; line-height: 1.2; text-align: center; font-weight: bold; white-space: pre;">


            <span style="color: var(--ascii-red)">██████╗</span> <span style="color: var(--ascii-yellow)">██╗</span> <span style="color: var(--ascii-green)">██████╗</span> <span style="color: var(--ascii-cyan)">██████╗</span> 
            <span style="color: var(--ascii-red)">██╔══██╗</span><span style="color: var(--ascii-yellow)">██║</span><span style="color: var(--ascii-green)">██╔════╝</span><span style="color: var(--ascii-cyan)">██╔═══██╗</span>
            <span style="color: var(--ascii-red)">  ██████╔╝</span><span style="color: var(--ascii-yellow)">██║</span><span style="color: var(--ascii-green)">██║     </span><span style="color: var(--ascii-cyan)">██║   ██║</span>  
            <span style="color: var(--ascii-red)">  ██╔═══╝ </span><span style="color: var(--ascii-yellow)">██║</span><span style="color: var(--ascii-green)">██║     </span><span style="color: var(--ascii-cyan)">██║   ██║</span>  
            <span style="color: var(--ascii-red)">  ██║     </span><span style="color: var(--ascii-yellow)">██║</span><span style="color: var(--ascii-green)">╚██████╗</span><span style="color: var(--ascii-cyan)">╚██████╔╝</span>  
            <span style="color: var(--ascii-red)">╚═╝     </span><span style="color: var(--ascii-yellow)">╚═╝</span> <span style="color: var(--ascii-green)">╚═════╝</span> <span style="color: var(--ascii-cyan)">╚═════╝</span> 
            </pre>
