services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped

    env_file:
      - .env

    command: tunnel run

    security_opt:
      - no-new-privileges:true

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - glance_default
      - homelab-filemgr_filemanager-net
      - big-bear-open-webui_default
      - vidown_vidown-network
      - swingmusic_default
      - anyconverter_default

networks:
  glance_default:
    external: true

  homelab-filemgr_filemanager-net:
    external: true

  big-bear-open-webui_default:
    external: true

  vidown_vidown-network:
    external: true
  
  swingmusic_default:
    external: true
  
  anyconverter_default:
    external: true


