services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host # Access Traefik via localhost:80 easily

    env_file:
      - .env

    command: tunnel run

    security_opt:
      - no-new-privileges:true

    extra_hosts:
      - "host.docker.internal:host-gateway"
